version: 2.1

jobs:
  create-infrastructure:
    docker:
      - image: cimg/aws:2023.09
    steps:
      - checkout
      - run:
          name: "Create EC2 Instance from cloudformation template"
          command: "aws cloudformation deploy \
            --template-file template.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}"

  configure-infrastructure:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - add_ssh_keys:
          # You can get this ID in the section where you registered the SSH Key
          fingerprints: ["13:9c:73:cf:5b:85:ec:c5:71:0a:38:01:e0:0d:d3:99"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible # Install Ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory playbook.yml
      - run:
          name: "Create EC2 Instance from cloudformation template"
          command: "aws cloudformation deploy \
            --template-file template.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}"

workflows:
  default:
    jobs:
      - create-infrastructure
