version: 2.1

jobs:
  create-infrastructure:
    docker:
      - image: cimg/aws:2023.09
    steps:
      - checkout
      - run:
          name: "Create EC2 Instance from cloudformation template"
          command: "aws cloudformation deploy \
            --template-file template.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}"

workflows:
  default:
    jobs:
      - create-infrastructure
